config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  root :to => 'posts#index'

  get 'static_pages/about'


  resources :posts do
  	resources :tags
  	 resources :comments
  end

    resources :tags do
  	  resources :posts
  	end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :admin
  validates :content, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :admin
  has_many :comments 
  has_and_belongs_to_many :tags
  
  validates :title, :presence => true
  validates :body, :presence => true

 end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts
  
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.new(comment_params)
    @comment.admin = current_admin
  	  if @comment.save
        respond_to do |format|
          format.html {redirect_to post_path(@post)}
          format.js
  	    end
  	  else
  	  	render :new
  	  end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.find(params[:id])
  	  if @comment.update(comment_params)
  	  	redirect_to post_path(@comment.post)
  	  else
  	  	render :edit
  	  end
  end

  def destroy
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.find(params[:id])
  	@comment.destroy
  	redirect_to post_path(@post)
  end

 private

  def comment_params
    params.require(:comment).permit(:content)
  end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :current_admin, only: [ :edit, :update, :destroy, :create ]
  
  def index
  	@posts = Post.all.sort_by{|post|
      (post.rating + ((1/(Time.new - post.created_at) * 1000)))
    }
    @posts.reverse!
  	@tags = Tag.all
  end

  def show
  	@post = Post.find(params[:id])
  end

  def new
  	@post = Post.new
  	@tags = Tag.all
  end

  def create
    @post = Post.new(post_params)
    @post.rating = 0
    tag_ids = params[:post][:tag]
  	if @post.save
      respond_to do |format|
        format.html { redirect_to posts_path }
        format.js
      end
        if tag_ids != nil
          if tag_ids.length > 0
            tag_ids.each do |tag_id|
              tag = Tag.find(tag_id)
              @post.tags.push(tag)
          end
        end
      end

    else
      render :new
    end
  end

  def edit
  	@post = Post.find(params[:id])
    @tags = Tag.all
      if params[:upvote]
        new_rating = @post.rating + 1
        @post.update(rating: new_rating)
        redirect_to posts_path
      end
  end

  def update
  	@post = Post.find(params[:id])
    tag_ids = params[:post][:tag]
  	if @post.update(post_params)
      if tag_ids == nil
        @post.tags.destroy_all()
      elsif tag_ids.length > 0
         tag_ids.each do |tag_id|
            tag = Tag.find(tag_id)
            @post.tags.push(tag)
          end
      end
      redirect_to posts_path
  	else
      render :edit
    end
  end

  def destroy
  	@post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

private
  def post_params
    params.require(:post).permit(:body, :title, :image)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find(params[:id])
  end
 
  def new 
  	@tag = Tag.new
  end
  
  def create
  	@tag = Tag.new(tag_params)
  	if @tag.save
  	  respond_to do |format|
        format.html { redirect_to posts_path }
        format.js
      end
  	else
  	  render :new
  	 end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
  	@tag = Tag.find(params[:id])
      respond_to do |format|
        format.html { redirect_to posts_path }
        format.js
      end
  	if @tag.update(tag_params)
  	else
  	  render :edit
  	end
  end

  def destroy
  	@tag = Tag.find(params[:id])
  	@tag.destroy
  	redirect_to posts_path
  end
 

private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= render "layouts/errors", :object => @comment %>

<%= form_for [@post, @comment] do |f| %>
  <div class="form-group">
    <%= f.label :content %>
    <br>
    <%= f.text_area :content, rows: "10", class: "form-control"%>
  </div>
    <%= f.submit "Post Comment", class: "btn btn-default center-block" %>
  <% end %>
  

app/views/comments/create.js.erb
$('form').remove();
('#new_post_comment_link').show();

app/views/comments/edit.html.erb
<div class = "container">
	<h1>Edit Comment</h1>
	<br>
	<%= render 'form' %>
</div>

app/views/comments/new.html.erb
<div class = "container">
  <h1>Leave a Comment</h1>
  <br>
  <%= render 'form' %>
</div>

app/views/comments/new.js.erb
$('#new_post_comment_link').hide().after('<%= j render("form") %>')

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/_header.html.erb
<div class="container">
  <% if current_admin %>
    <div class="admin-display">
      Welcome, <%= current_admin.email %>!
      <%= link_to 'Logout', destroy_admin_session_path, method: :delete, class:"btn btn-default" %>
    </div>
  <% else %>
    <div class ="buttons-display">
      <%= link_to 'Login', new_admin_session_path, class:"btn btn-default"%>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coding Lady</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,300,700' rel='stylesheet' type='text/css'>
</head>

 <% if notice || alert %>
  <div id="alert-row" class="row">
    <% if notice %>
    <div class="alert alert-success"><%= notice %></div>
    <% end %>
    <% if alert %>
    <div class="alert alert-danger"><%= alert %></div>
    <% end %>
  </div>
  <% end %>

<body>
  <div class="container">
  <div class="jumbotron main-jumbotron">
    <br>
    <br>
    <br>
    <br>
    <h1 class="title">Coding Lady</h1>
    <br>
      <div class="navbar-header">
        <ul class= "nav navbar-nav navbar-center">
          <li><a class="navbar-link" href="/static_pages/about">About</a></li>
        </ul>
        <ul class= "nav navbar-nav navbar-center">
          <li><a class="navbar-link" href="/">Home</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<hr>



<div class="container-fluid">
  <%= yield %>
   </body>
</div>
<br>
<br>
</div>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>


<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <br>
    <%= f.text_area :body, rows: "10", class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :image%>
    <%= f.text_field :image, class: "form-control"%>
  </div>
   <% if @tags %>
     <% @tags.each do |tag| %>
      <%= check_box_tag :tags, tag.id, @post.tags.include?(tag), :name => 'post[tag][]' %>
      <%= label_tag :tags, tag.name %>
    <% end %>
   <% end %>
    <%= f.submit "Submit", class: "btn btn-default center-block" %>
  <% end %>
  

app/views/posts/create.js.erb
$('form').remove();
('#new_post_link').show();

app/views/posts/edit.html.erb
<div class = "container">
<h1>Edit Post</h1>
<br>
<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="container">
<ul>
  <% @posts.each do |post| %>
    <li>
    <br>
      <div class="post-display">
        <%= link_to post.title, post_path(post) %>
        <%= link_to content_tag(:span, "", class:"glyphicon glyphicon-thumbs-up"),
        edit_post_path(post.id, upvote: true) %> <small> <%= post.rating %></small>
      </div>
      <small>Posted: <%= post.created_at.time.to_formatted_s(:long) %>, </small>
      <small>Comments: <%= post.comments.count %></small>
     <br>
     <hr>
    </li>
  <% end %>
</ul>
<span class="glyphicon"></span>
<br>
<div class="container">
  <% if admin_signed_in? %>
    <% if !current_admin.user %>
    <%=link_to "New Post", new_post_path, id: "new_post_link", class: "btn btn-success",remote: true %>
    <% end %>
  <% end %>
</div>


<div class="container">
  <h3> Tags </h3>
  <ul>
    <% @tags.each do |tag| %>
    <br>
      <li> <%= link_to tag.name,  tag_path(tag) %> </li>
        <% if admin_signed_in? %>
          <% if !current_admin.user %>
            <%=link_to "Edit", edit_tag_path(tag), class:"btn btn-default", id:"edit_tag_link", remote:true %>
            <%=link_to "Delete Tag", tag_path(tag),
                              :data => {:confirm =>"You sure?",
                              :method => "delete"}, class:"btn btn-default" %>
          <% end %>
        <% end %>
    <% end %>
  <br>
  <br>
    <% if admin_signed_in? %>
      <% if !current_admin.user %>
        <%=link_to "Add Tag", new_tag_path, id: "new_tag_link", class: "btn btn-success", remote: true %>
      <% end %>
    <% end %>
  </ul>
</div>


<%= render 'layouts/header' %>


</div>

app/views/posts/new.html.erb
<div class = "container">
  <h1>New Post</h1>
  <br>
  <%= render 'form' %>
</div>

app/views/posts/new.js.erb
$('#new_post_link').hide().after('<%= j render("form") %>')

app/views/posts/show.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="post-header">
    <%= @post.title %>
  </div>
<hr>
  <div class="post-body">
    <%= @post.body %>
  </div>
<br>
<br>
  <% if admin_signed_in? %>
    <% if !current_admin.user %>
      <li><p><%= link_to "Edit", edit_post_path(@post), class:"btn btn-default" %>
           <%= link_to "Delete", post_path(@post),
                                :data => {:confirm =>"You sure?",
                                :method => "delete"}, class:"btn btn-default" %></p></li>
    <% end %>
  <% end %>
<ul>
  Tags:
  <% @post.tags.each do |tag| %>
    <li><%= link_to tag.name,  tag_path(tag) %> </li>
  <% end %>
</ul>
<hr>

<% if admin_signed_in? %>
  <%=link_to "Leave a comment", new_post_comment_path(@post), class:"btn btn-default", id:"new_post_comment_link", remote:true %>
<% else %> Want to leave a comment?
  <%= link_to 'Sign-Up', new_admin_registration_path, class:"btn btn-default" %> or
  <%= link_to 'Login', new_admin_session_path, class:"btn btn-default"%>
<% end %>
<br>
<br>

<% if @post.comments.any? %>
  <% @post.comments.each do |comment| %>
    <%= comment.content %>
    <%= comment.admin.email %> says...
    <li><%=comment.created_at.time.to_formatted_s(:long) %></li>
      <% if admin_signed_in?  %>
        <%= link_to "Edit Comment", edit_post_comment_path(@post, comment), class:"btn btn-default" %>
        <%= link_to "Delete Comment", post_comment_path(@post, comment),
                                  :data => {:confirm =>"You sure?",
                                  :method => "delete"}, class:"btn btn-default" %>
      <% end %>
      <br>
  <% end %>
<% end %>
</div>

app/views/static_pages/about.html.erb
<div class="container">
<h1>Hey there!</h1>
<p>My name is Jessica Joly and I'm the coding lady</p>
</div>

app/views/tags/_form.html.erb
<%= render "layouts/errors", :object => @tag %>

<center>
<%= form_for @tag do |f| %>
  <div class="form-group">
    <%= f.label :tag %>
    <%= f.text_field :name %>
  </div>
    <%= f.submit "Submit" %>
  <% end %>
</center>

app/views/tags/create.js.erb
$('form').remove();
('#new_tag_link').show();

app/views/tags/edit.html.erb
<center>
<h1>Update a tag</h1>
</center>
<br>
<br>

<%= render 'form' %>

app/views/tags/edit.js.erb
$('#edit_tag_link').hide().after('<%= j render("form") %>')

app/views/tags/new.html.erb
<div class = "container">
<h1>Add a tag</h1>
<br>
<br>
<%= render 'form' %>
</div>

app/views/tags/new.js.erb
$('#new_tag_link').hide().after('<%= j render("form") %>')

app/views/tags/show.html.erb
<center>
<h1><%= @tag.name %></h1>
</center>
<li>Tagged Posts:</li>
<hr>
<div class = "container">
  <ul>
  <% @tag.posts.order(created_at: :desc).each do |post| %>
    <%= link_to post.title, post_path(post) %>
  <% end %>
  </ul>
</div>

app/views/tags/update.js.erb
$('form').remove();
('#edit_tag_link').show();